ExpenseTracker/Controllers/ExpenditureController.cs
using ExpenseTracker.Data;
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ExpenseTracker.Controllers
{
    public class ExpenditureController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExpenditureController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Expenditure> objList = _db.Expenditures;
            foreach (var obj in objList)
            {
                obj.ExpenditureType = _db.ExpenditureTypes.FirstOrDefault(u => u.Id == obj.ExpenditureTypeId);
            }
            return View(objList);

        }

        //Get - Create
        public IActionResult Create()
        {
            IEnumerable<SelectListItem> TypeDropDown = _db.ExpenditureTypes.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()

            });

            ViewBag.TypeDropDown = TypeDropDown;

            return View();
        }

        //Post - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expenditure obj)
        {

            //Server side Validation
            if (ModelState.IsValid)
            {
                //obj.ExpenditureTypeId = 1;
                _db.Expenditures.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
           return View(obj);
        }

        // GET-Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Expenditures.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            var obj = _db.Expenditures.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Expenditures.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET-Update
        [HttpGet]
        public IActionResult Update(int? Id)
        {
            IEnumerable<SelectListItem> TypeDropDown = _db.ExpenditureTypes.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()

            });

            ViewBag.TypeDropDown = TypeDropDown;

            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Expenditures.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Expenditure obj)
        {
            if (ModelState.IsValid)
            {
                _db.Expenditures.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

ExpenseTracker/Controllers/ExpenditureTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ExpenseTracker.Data;
using ExpenseTracker.Models;
using System.Collections.Generic;

namespace ExpenseTracker.Controllers
{
    public class ExpenditureTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ExpenditureTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ExpenditureType> objList = _db.ExpenditureTypes;
            return View(objList);

        }

        //Get - Create
        public IActionResult Create()
        {
            return View();
        }

        //Post - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenditureType obj)
        {

            //Server side Validation
            if (ModelState.IsValid)
            {
                _db.ExpenditureTypes.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
           return View(obj);
        }

        // GET-Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.ExpenditureTypes.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST-Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            var obj = _db.ExpenditureTypes.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.ExpenditureTypes.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET-Update
        public IActionResult Update(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.ExpenditureTypes.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST-Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ExpenditureType obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpenditureTypes.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

ExpenseTracker/Controllers/ItemController.cs
using ExpenseTracker.Data;
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ExpenseTracker.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Items;
            return View(objList);
        }
        //Always pathparameters id should be unique and if we want to 
        //use queryparameter irrespective of keyword we need to use ? in url
        public string GetName(int id,int id1)
        {
            return "Welcome " + id + "Name: " +id1;
        }

        //Get - Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Post - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Items.Add(obj); 
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ExpenseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-expand-sm navbar-toggleable-sm navbar bg-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white">ExpenseTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Expenditure" asp-action="Index">My Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ExpenditureType" asp-action="Index">My Expense Types</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExpenseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>